[package]
name = "alexandria_proof"
version = "0.1.0"
description = "Starknet storage proof verifier"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/src/proof"

[dependencies]
starknet.workspace = true
