name: Gas Report

on:
  pull_request:
    branches: [main]

jobs:
  gas-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1.3.2

      - name: Generate and compare gas report
        run: |
          ./scripts/generate_gas_report.sh
        shell: bash