name: test

on: [push, pull_request]

env:
  CAIRO_COMPILER_VERSION: v1.0.0
  ARCHIVE_LINK: https://github.com/starkware-libs/cairo/releases/download/v1.0.0/release-x86_64-unknown-linux-musl.tar.gz
  ARCHIVE_NAME: cairo.zip

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Downloading binaries
        run: curl -L -o $ARCHIVE_NAME $ARCHIVE_LINK
      - name: Step 3 - Unzipping binaries
        run: tar -xvf $ARCHIVE_NAME
      - name: Step 4 - Make binaries available
        run: echo "./cairo/bin" >> $GITHUB_PATH
      - name: Step 5 - Trying to build
        run: make build

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Downloading binaries
        run: curl -L -o $ARCHIVE_NAME $ARCHIVE_LINK
      - name: Step 3 - Unzipping binaries
        run: tar -xvf $ARCHIVE_NAME
      - name: Step 4 - Make binaries available
        run: echo "./cairo/bin" >> $GITHUB_PATH
      - name: Step 5 - Running tests
        run: make test

  check-format:
    name: check-format
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Downloading binaries
        run: curl -L -o $ARCHIVE_NAME $ARCHIVE_LINK
      - name: Step 3 - Unzipping binaries
        run: tar -xvf $ARCHIVE_NAME
      - name: Step 4 - Make binaries available
        run: echo "./cairo/bin" >> $GITHUB_PATH
      - name: Step 5 - Checking formatting
        run: make check-format
      