name: test

on: [push, pull_request, pull_request_target]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: starkrocket/cairo-cli:latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Compile
          cairo-compile src
          # Run tests
          cairo-run --path src/fibonacci.cairo
          cairo-run --path src/perfect_number.cairo
