name: test

on: [push, pull_request]

env:
  CAIRO_COMPILER_VERSION: 1.0.0-alpha.2
  # Temporary use artifacts from custom CI build
  ARTIFACT_RELEASE_ARCHIVE_LINK: https://api.github.com/repos/starkware-libs/cairo/actions/artifacts/533097268/zip
  ARTIFACT_RELEASE_ARCHIVE_NAME: cairo.zip
  RELEASE_ARCHIVE_NAME: x86_64-unknown-linux-musl.tar.gz

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o $ARTIFACT_RELEASE_ARCHIVE_NAME $ARTIFACT_RELEASE_ARCHIVE_LINK
          unzip $ARTIFACT_RELEASE_ARCHIVE_NAME
          tar -xvf $RELEASE_ARCHIVE_NAME
          export PATH=$PATH:$(pwd)/cairo/bin
          make build

  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o $ARTIFACT_RELEASE_ARCHIVE_NAME $ARTIFACT_RELEASE_ARCHIVE_LINK
          unzip $ARTIFACT_RELEASE_ARCHIVE_NAME
          tar -xvf $RELEASE_ARCHIVE_NAME
          export PATH=$PATH:$(pwd)/cairo/bin
          # TODO: uncomment when demo is ready
          #make run

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o $ARTIFACT_RELEASE_ARCHIVE_NAME $ARTIFACT_RELEASE_ARCHIVE_LINK
          unzip $ARTIFACT_RELEASE_ARCHIVE_NAME
          tar -xvf $RELEASE_ARCHIVE_NAME
          export PATH=$PATH:$(pwd)/cairo/bin
          make test
